version: "3"

services:

  mysql-db:
    image: mysql:8.0.23
    container_name: mysql-db
    hostname: database
    restart: unless-stopped
    volumes:
      - mysql-tour-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=book_store_db

volumes:
  mysql-tour-data:
