spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://${DATABASE_HOSTNAME:localhost}:3306/tour_db?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  liquibase:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false